#!/bin/bash

# Email Worker Testing Script
# This script helps test the deployed email worker

echo "═══════════════════════════════════════════════════════════════"
echo "🧪 Email Worker Testing Guide"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ Worker Deployed: chittyos-email-worker"
echo "📍 Worker URL: https://chittyos-email-worker.chittycorp-llc.workers.dev"
echo "🆔 Version: 68d101f2-de01-46bc-92bd-c26f107fd9f9"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📋 CONFIGURATION CHECKLIST"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "□ Enable Email Routing for domain in Cloudflare Dashboard"
echo "□ Add DNS MX records (done automatically)"
echo "□ Create Email Worker route (*@chitty.cc → chittyos-email-worker)"
echo "□ Add and verify destination address (no-reply@itcan.llc)"
echo "□ Test with sample email"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "🔗 Quick Links"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Cloudflare Dashboard:"
echo "  https://dash.cloudflare.com/0bc21e3a5a9de1a4cc843be9c3e98121"
echo ""
echo "Email Routing Setup:"
echo "  1. https://dash.cloudflare.com/0bc21e3a5a9de1a4cc843be9c3e98121/chitty.cc/email/routing/overview"
echo "  2. Click 'Email Workers' tab"
echo "  3. Click 'Create Email Worker Route'"
echo "  4. Set matcher: *@chitty.cc"
echo "  5. Select worker: chittyos-email-worker"
echo "  6. Save and enable"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📧 TEST EMAILS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Test 1: Basic Reception"
echo "  To: test@chitty.cc"
echo "  Subject: Test Email"
echo "  Body: Testing basic email reception"
echo ""
echo "Test 2: Legal Classification"
echo "  To: legal@chitty.cc"
echo "  Subject: Urgent: Arias v Bianchi Case 2024D007847"
echo "  Body: Need immediate review of court documents"
echo "  Expected: Classified as 'litigation', urgency 'critical'"
echo ""
echo "Test 3: BCC Tracking (Certified)"
echo "  To: someone@example.com"
echo "  BCC: bcc@chitty.cc"
echo "  Expected: Certified delivery tracking logged"
echo ""
echo "Test 4: Finance Email"
echo "  To: billing@chitty.cc"
echo "  Subject: Invoice #12345 - Payment Due"
echo "  Expected: Classified as 'finance' workstream"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "🔍 MONITORING"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "View real-time logs:"
echo "  wrangler tail chittyos-email-worker --format pretty"
echo ""
echo "Check Email Routing analytics:"
echo "  https://dash.cloudflare.com/0bc21e3a5a9de1a4cc843be9c3e98121/chitty.cc/email/routing/analytics"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "🚀 START MONITORING"
echo "═══════════════════════════════════════════════════════════════"
echo ""
read -p "Start monitoring worker logs? (y/n) " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "Starting log monitoring..."
    wrangler tail chittyos-email-worker --format pretty
fi
